### ISSUE TITLE
Selection: Is it possible to expose an `onClick` callback?

### ISSUE THREAD

**Issue by andywhite37** [mlms13/FancyTable#34]
Right now fancy table selects the cell on single-click, and calls `onRangeChange` if the selection changed, but it would be handy to get a `onClick` callback (always), even if the selection didn't change.

This would be useful because the design calls for single-clicking the "active" cell to make it go into the editable input mode, and right now, I would have to wire the click myself to get this behavior, but it seemed like since FancyTable is exposing `onDoubleClick` it's not unreasonable to expose `onClick` too.

Note: I also plan on typing in the "active" cell making it go into the editable input mode.

**Comment by fponticelli** [comment]
I can give you the event but we should not go in edit mode on single click. Neither excel or google preadsheet does that. The main reason to avoid it is because it kills the navigation using arrows. If you are in edit mode the arrows should navigate you inside the input control.

**Comment by andywhite37** [comment]
I agree.  I was just asking because it was requested in this issue. 
 https://github.com/pellucidanalytics/pellucid-tasks/issues/508.  But I think your point overrides the design, and is the right thing to do.
