### ISSUE TITLE
Selection: home, end, page-up, page-down keys

### ISSUE THREAD

**Issue by andywhite37** [mlms13/FancyTable#36]
Also, if there is a key-combo to scroll all the way to the top or bottom of the grid... not sure what the standard key(s) are for that.

These would be nice to support (not only navigation, but for range selection?)

**Comment by fponticelli** [comment]
Yeah, I planned to wire: `home`, `end`, `CMD/CTRL+arrows`, `page` keys

**Comment by andywhite37** [comment]
What a professional
