### ISSUE TITLE
Reliance on KeyboardEvent.key can cause problems at this point in time

### ISSUE THREAD

**Issue by andywhite37** [mlms13/FancyTable#50]
We are using `KeyboardEvent.key` to trigger different actions, which is not a 100% available property:  https://github.com/mlms13/FancyTable/blob/master/src/fancy/table/KeyEvent.hx#L10

Here is an example polyfill:  https://github.com/cvan/keyboardevent-key-polyfill/blob/master/index.js

The fix we discussed was to add a function to `dots` like this:

```
enum Key {
  Character(c: String);
  Other(v: NonCharacterKey);
}

enum NonCharacterKey {
  Enter;
  Tab;
  Arrow...
}

class KeyboardEvents { // or KeyboardEventExtensions?
  public static function getKey(e : KeyboardEvent) : Key {
    // if key is not null - use that to map to `Key`
    // if key is null, use which or keyCode to map to `Key`
  }
}
```

Then we should use this `dots` function in `FancyTable` for constructing the custom `KeyEvent`

**Comment by mlms13** [comment]
This is probably fixed in master. We have much more robust (but slightly under-tested) key handling.
